version: '2'
services:
  bot:
    build: .
    restart: always
    expose:
      - 80
    environment:
      VIRTUAL_HOST: ${HOST}
      LETSENCRYPT_HOST: ${HOST}
      LETSENCRYPT_EMAIL: ${EMAIL}

networks:
  default:
    external:
      name: nginx-proxy
